name: ima_player
description: iOS, Android supported IMA Player. Used ExoPlayer for Android and AVPlayer for iOS.
version: 1.2.0
homepage: https://github.com/GeceGibi/ima_player

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.gece.imaplayer
        pluginClass: ImaPlayerPlugin
      ios:
        pluginClass: ImaPlayerPlugin