name: ima_player
description: iOS, Android supported IMA Player. Used ExoPlayer for Android and AVPlayer for iOS.
version: 2.0.6
homepage: https://github.com/GeceGibi/ima_player

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
    
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.gece.imaplayer
        pluginClass: ImaPlayerPlugin
      ios:
        pluginClass: ImaPlayerPlugin